name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Create Build Directory
      run: make_directory ${{github.workspace}}/build
    - name: Install Packages
      run: |
        sudo apt-get update -qq
        sudo apt-get install build-essential
    - name: Configure Emscripten
      shell: bash
      # Change the directory to be emsdk instead of the project root
      working-directory: ${{github.workspace}}\analytics\C\udataDatabase
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
