name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Packages
      run: |
        sudo apt-get update -qq
        sudo apt-get install build-essential
        run: echo package install!
        
    - name: Configure Test
      shell: bash
      # Change the directory to be 
      working-directory: ${{github.workspace}}\ci_test\analytics\C\udataDatabase
      run: echo pwd!
      
    - name: make
      run: make
      
    - name: make check
      run: make check
      
    - name: make distcheck
      run: make distcheck
